baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '''jreyesr's blog'''
theme = 'anubis'
timeZone = "America/Guayaquil"

ignoreLogs = ['warning-goldmark-raw-html']
ignoreFiles = ['posts/*/observable/dist/*.html', 'posts/*/observable/*']

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[params]
author = 'jreyesr'
style = 'auto'
readMore = true
rssAsSocialIcon = true
math = true

utterancesRepo = "jreyesr/jreyesr.github.io"
utterancesTheme = "preferred-color-scheme"
utterancesIssue = "pathname"
utterancesLabel = "utteranc.es"


[[params.social]]
id = "github"
url = "https://github.com/jreyesr"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
